﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace NFLModel
{
    public partial class PointsPredictor
    {
        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"Our Yards", @"Our Yards"),new InputOutputColumnPair(@"Our TOs", @"Our TOs"),new InputOutputColumnPair(@"Their Pts", @"Their Pts"),new InputOutputColumnPair(@"Their Yards", @"Their Yards"),new InputOutputColumnPair(@"Their TOs", @"Their TOs")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"Our Yards",@"Our TOs",@"Their Pts",@"Their Yards",@"Their TOs"}))      
                                    .Append(mlContext.Transforms.NormalizeMinMax(@"Features", @"Features"))      
                                    .Append(mlContext.Regression.Trainers.LbfgsPoissonRegression(new LbfgsPoissonRegressionTrainer.Options(){L1Regularization=15.37015F,L2Regularization=1.600315F,LabelColumnName=@"Our Pts",FeatureColumnName=@"Features"}));

            return pipeline;
        }
    }
}
