
// This file was auto-generated by ML.NET Model Builder. 

using NFLModel;

PointsPredictor.ModelInput sampleData = new PointsPredictor.ModelInput()
{
    Our_Yards = 368F,
    Our_TOs = 1F,
    Their_Pts = 20F,
    Their_Yards = 316F,
    Their_TOs = 1F,
};

// Make a single prediction on the sample data and print results
var predictionResult = PointsPredictor.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Our_Pts with predicted Our_Pts from sample data...\n\n");


Console.WriteLine($"Our_Pts: {21F}");
Console.WriteLine($"Our_Yards: {368F}");
Console.WriteLine($"Our_TOs: {1F}");
Console.WriteLine($"Their_Pts: {20F}");
Console.WriteLine($"Their_Yards: {316F}");
Console.WriteLine($"Their_TOs: {1F}");


Console.WriteLine($"\n\nPredicted Our_Pts: {predictionResult.Score}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

